language: python

sudo: false

python:
  - "3.6"

install:
  - pip install -e .

script:
  - make demo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: demo/output
  on:
    branch: master
